# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  paths:
    include:
    - server-node-app/*
    exclude:
    - bicep/*
    - client-react-app/*
  branches:
    include:
    - main
variables:
  path: 'server-node-app'
  zipPath: 'server-node-app/'
pool:
  vmImage: windows-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
- script: |
    cd $(path)
    npm install
    cd ..
  displayName: 'npm install'
- script: |
    cd $(path)
    npm run lint
  displayName: 'npm run lint'
- task: ArchiveFiles@2
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    rootFolderOrFile: '$(zipPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop_server'
    publishLocation: 'Container'
