trigger:
  paths:
    include:
    - client-react-app/*
    exclude:
    - bicep/*
    - server-node-app/*
  branches:
    include:
    - main

variables:
  path: 'client-react-app'
  buildPath: 'client-react-app/build'

pool:
  vmImage: windows-latest

stages:
  - stage: build
    displayName: 'Build Artifact'
    jobs:
    - job: 'build'
      displayName: 'Initialize Project'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js'

      - script: |
          cd $(path)
          npm install
          cd ..
        displayName: 'npm install'

      - script: |
          cd $(path)
          npm run build
          popd
          cd ..
        displayName: 'npm run build'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(buildPath)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'drop_client'
          publishLocation: 'pipeline'

